default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nyumonkadai_development

test:
  <<: *default
  database: nyumonkadai_test

production:
  <<: *default
  database: nyumonkadai_production
  username: nyumonkadai
  password: <%= ENV['NYUMONKADAI_DATABASE_PASSWORD'] %>
